students:
  - email: vchernoy@gmail.com
    offerings:
      - investing-basics-2026-05
      - roth-ira-webinar-2026-04

  - email: student1@example.com
    offerings:
      - investing-basics-2026-05
      - roth-ira-webinar-2026-04

  - email: student2@example.com
    offerings:
      - investing-basics-2026-05
      - roth-ira-webinar-2026-04

  - email: alenatravel@gmail.com
    offerings:
      - investing-basics-2026-05
      - roth-ira-webinar-2026-04
  
  - email: natalya.fominykh@gmail.com
    offerings:
      - investing-basics-2026-05
